apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://kubernetes.github.io/cert-manager
    chart: cert-manager
    targetRevision: 4.11.2
    helm:
      values: |
        controller:
          replicaCount: 1
          service:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-resource-group: <your-azure-resource-group>
            externalTrafficPolicy: Local
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
