apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8-cluster-azure-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cg-manish/k8-playground.git
    targetRevision: argo-management-cluster
    path: apps-base-chart/
    helm:
      # valueFiles:
      #   - clusters/k8-cluster-azure-dev/values.yaml
      values: |
        cluster:
          name: k8-dev-cluster
        destination:
          server: https://k8-dev-cluster-dns-vjuoo8om.hcp.southindia.azmk8s.io:443
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
