apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8-cluster-azure-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cg-manish/k8-playground.git
    targetRevision: argo-management-cluster
    path: apps-base-chart
    helm:
      valueFiles:
        - ./values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
