apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: ''
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: 'bootstrapp/app-of-apps'
    repoURL: https://github.com/cg-manish/k8-automation.git
    targetRevision: argo-management-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
project: default
source:
  repoURL: https://github.com/cg-manish/k8-automation.git
  path: clusters/
  targetRevision: argo-management-cluster
  directory:
    recurse: true
    jsonnet: {}
destination:
  server: https://kubernetes.default.svc
  namespace: argocd
syncPolicy:
  automated:
    prune: true
    selfHeal: true
