apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    server: <cluster-api-server-url>
    namespace: cert-manager
  source:
    repoURL: https://github.com/your-org/argo-apps.git
    path: apps/cert-manager
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
