apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'ingress-nginx-{{.Values.cluster.name}}'
  namespace: argocd
spec:
  destination:
    server: {{.Values.destination.server}}
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.2
    helm:
      values: |
        controller:
          replicaCount: 1
          service:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-resource-group: <your-azure-resource-group>
            externalTrafficPolicy: Local
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
