apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: not-test-app
  namespace: argocd
spec:
  destination:
    server: https://k8-dev-cluster-dns-vjuoo8om.hcp.southindia.azmk8s.io:443
    namespace: not-test-app
  source:
    repoURL: https://github.com/cg-manish/k8-playground.git
    targetRevision: argo-management-cluster
    path: sample-apps/
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
