apiVersion: v1
kind: Service
metadata:
  name: '{{.Values.app_name}}-service'
spec:
  selector:
    app: {{.Values.app_name}}
  type: {{.Values.service.type}}
  ports:
  - protocol: TCP
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.targetPort}}
