apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: sample-app-service
spec:
  selector:
    app: sample-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
=======
  name: '{{.Values.app_name}}-service'
spec:
  selector:
    app: {{.Values.app_name}}
  type: {{.Values.service.type}}
  ports:
  - protocol: TCP
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.targetPort}}
>>>>>>> master
