apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-local-chart-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: HEAD
    path: my-local-chart
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://k8-dev-cluster-dns-vjuoo8om.hcp.southindia.azmk8s.io:443
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
