apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'cert-issuer-{{ .Values.cluster.name }}'
  namespace: argocd
spec:
  destination:
    server: {{ .Values.destination.server }}
    namespace: cert-manager
  source:
    repoURL: https://github.com/cg-manish/k8-playground.git
    targetRevision: argo-management-cluster
    path: core/cert-issuer/apps
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
