apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-community/prometheus-operator-crds
    targetRevision: "15.0.0"
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply="true"
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
